AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  register.svc

  Sample SAM Template for register.svc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  RegisterApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: Prod
        DefinitionBody:
          swagger: "2.0"
          info:
            title: Register API
            version: "1.0"

        Models:
          UrlCreationModel:
            type: object
            required:
              - url
            properties:
              url:
                type: string

  RegisterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Register:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /register/
            Method: POST
            RestApiId: !Ref RegisterApi
            RequestModel:
              Model: UrlCreationModel
              Required: true
    Metadata:
      DockerTag: java25-maven-v1
      DockerContext: ./RegisterFunction
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RegisterApi:
    Description: "API Gateway endpoint URL for Prod stage for Register function"
    Value: !Sub "https://${RegisterApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/register/"
  RegisterFunction:
    Description: "Register Lambda Function ARN"
    Value: !GetAtt RegisterFunction.Arn
  RegisterFunctionIamRole:
    Description: "Implicit IAM Role created for Register function"
    Value: !GetAtt RegisterFunctionRole.Arn
