AWSTemplateFormatVersion: '2010-09-09'
Description: Security Groups

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda SG
      VpcId: !ImportValue AppVpcId

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Redis SG
      VpcId: !ImportValue AppVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref LambdaSecurityGroup

Outputs:
  LambdaSecurityGroupId:
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: LambdaSecurityGroupId

  RedisSecurityGroupId:
    Value: !Ref RedisSecurityGroup
    Export:
      Name: RedisSecurityGroupId
